name: SVC
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10.14
  - pip
  - einops==0.8.1
  - ipykernel==7.1.0
  - pandas==2.2.3
  - seaborn==0.13.2
  - pip:
    - gseapy==1.1.11
    - local-attention==1.9.15
    - matplotlib==3.9.2
    - natsort==8.4.0
    - networkx==3.4.2
    - numba==0.61.0
    - numpy==1.26.4
    - scanpy==1.10.3
    - scikit-learn==1.5.2
    - scipy==1.12.0
    - tifffile==2024.9.20
    - torch==2.5.1
    - tqdm==4.66.5
    - umap-learn==0.5.6
    
    
    